name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Start and set up PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          echo "ALTER USER postgres WITH PASSWORD 'postgres'" | sudo -u postgres psql

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Test
        run: make test
